#latest version
#1
#Table: Company
CREATE TABLE COMPANY(
COMPANY_NAME VARCHAR(25) NOT NULL,
HQ_ADDRESS VARCHAR(25),
INCOME_OUTCOME INT,
NUMBER_OF_SALESMEN INT,
NUMBER_OF_FACTORIES INT,
DRUG_RATE INT,
PRIMARY KEY(COMPANY_NAME)
);
#2
#Table: State Deposit of Pharmaceuticals (Entity)
CREATE TABLE STATE_DEPOSIT_OF_PHARMACEUTICALS(
CITY VARCHAR(25) NOT NULL,
SDOP_RANGE INT,
SDOP_CAPACITY INT,
ADDRESS VARCHAR(25),
SDOP_DELIVERY_TIME INT,
PRIMARY KEY (CITY)
);
#3
#Table: Doctor (Entity)
CREATE TABLE DOCTOR(
DOCTOR_SSN INT NOT NULL,
DOCTOR_NAME VARCHAR(25),
AGE INT,
EXPERIENCE_YEARS INT,
SPECIALTY VARCHAR(25),
PRIMARY KEY (DOCTOR_SSN)
);
#4
#Table: Patient (Entity)
CREATE TABLE PATIENT(
PATIENT_SSN INT NOT NULL,
PATIENT_NAME VARCHAR(25),
AGE INT,
GENDER BOOLEAN,
PHONE_NUMBER BIGINT,
PRIMARY KEY (PATIENT_SSN)
);
#5
#Table: Drugs (Entity)
CREATE TABLE DRUG(
SERIAL_CODE BIGINT NOT NULL,
COMPANY_NAME VARCHAR(25) NOT NULL,
DRUG_NAME VARCHAR(25),
TYPE VARCHAR(25),
APPROVAL BOOLEAN,
PRICE DECIMAL(8,3),
PRIMARY KEY(SERIAL_CODE,COMPANY_NAME),
FOREIGN KEY(COMPANY_NAME) REFERENCES COMPANY(COMPANY_NAME)
);
#6
#Table: Salesman
CREATE TABLE SALESMAN(
SALESMAN_NAME VARCHAR(25),
SALESMAN_SSN INT NOT NULL,
COMPANY_NAME VARCHAR(25),
DRUG_SERIAL_CODE BIGINT NOT NULL,
EXPERIENCE INT,
SALARY DECIMAL(8,3),
PRIMARY KEY(SALESMAN_SSN),
FOREIGN KEY(COMPANY_NAME) REFERENCES COMPANY(COMPANY_NAME),
FOREIGN KEY (DRUG_SERIAL_CODE) REFERENCES DRUG(SERIAL_CODE)
);
#7
#Table: Distributor
CREATE TABLE DISTRIBUTOR(
DISTRIBUTOR_NAME VARCHAR(25) NOT NULL,
DISTR_POINTS INT,
DISTR_CAPACITY INT,
MEAN_DISTR_TIME INT,
DISTR_RANGE_Km INT,
PRIMARY KEY(DISTRIBUTOR_NAME)
);
#8
#Table: Prescription (Entity)
CREATE TABLE PRESCRIPTION(
COMPANY_NAME VARCHAR(25) NOT NULL,
SERIAL_CODE BIGINT NOT NULL,
PATIENT_SSN INT NOT NULL,
DISEASE_CODE CHAR(3),
DATE_OF_PRESCRIPTION DATE,
PRIMARY KEY (SERIAL_CODE, COMPANY_NAME),
FOREIGN KEY (SERIAL_CODE) REFERENCES DRUG (SERIAL_CODE),
FOREIGN KEY (COMPANY_NAME) REFERENCES COMPANY (COMPANY_NAME),
FOREIGN KEY (PATEIENT_SSN) REFERENCES PATIENT (PETIENT_SSN)
);

#1
#Table: History (Relationship)
CREATE TABLE HISTORY(
PATIENT_SSN INT NOT NULL,
COMPANY_NAME VARCHAR(25) NOT NULL,
SERIAL_CODE BIGINT NOT NULL,
MONTHS_PER_DOSE INT,
PRIMARY KEY (PATIENT_SSN, COMPANY_NAME, SERIAL_CODE),
FOREIGN KEY (PATIENT_SSN) REFERENCES PATIENT (PATIENT_SSN),
FOREIGN KEY (SERIAL_CODE) REFERENCES DRUG (SERIAL_CODE),
FOREIGN KEY (COMPANY_NAME) REFERENCES COMPANY (COMPANY_NAME)
);

#2
#Table: Distribute (Relationship)
CREATE TABLE DISTRIBUTE(
DISTRIBUTOR_NAME VARCHAR(25) NOT NULL,
COMPANY_NAME VARCHAR(25) NOT NULL,
SERIAL_CODE BIGINT NOT NULL,
DAYS_UNTIL_DELIVERY INT,
PRIMARY KEY (DISTRIBUTOR_NAME, COMPANY_NAME, SERIAL_CODE),
FOREIGN KEY (DISTRIBUTOR_NAME) REFERENCES DISTRIBUTOR (DISTRIBUTOR_NAME),
FOREIGN KEY (COMPANY_NAME) REFERENCES COMPANY (COMPANY_NAME),
FOREIGN KEY (SERIAL_CODE) REFERENCES DRUG (SERIAL_CODE)
);

#3
#Table: Sell (Relationship)
CREATE TABLE SELL(
CITY VARCHAR(25) NOT NULL,
DISTRIBUTOR_NAME VARCHAR(25) NOT NULL,
PRIMARY KEY (CITY, DISTRIBUTOR_NAME),
FOREIGN KEY (CITY) REFERENCES STATE_DEPOSIT_OF_PHARMACEUTICALS (CITY),
FOREIGN KEY (DISTRIBUTOR_NAME) REFERENCES DISTRIBUTOR (DISTRIBUTOR_NAME)
);

#4
#Table: Provides (Relationship)
CREATE TABLE PROVIDES(
CITY VARCHAR(25) NOT NULL,
SERIAL_CODE BIGINT NOT NULL,
COMPANY_NAME VARCHAR(25) NOT NULL,
PRIMARY KEY (CITY, SERIAL_CODE, COMPANY_NAME),
FOREIGN KEY (CITY) REFERENCES STATE_DEPOSIT_OF_PHARMACEUTICALS (CITY),
FOREIGN KEY (SERIAL_CODE) REFERENCES DRUG (SERIAL_CODE),
FOREIGN KEY (COMPANY_NAME) REFERENCES DRUG (COMPANY_NAME)
);

#5
#Table: Buy (Relationship)
CREATE TABLE BUY(
COMPANY_NAME VARCHAR(25) NOT NULL,
DISTRIBUTOR_NAME VARCHAR(25) NOT NULL,
PRIMARY KEY (COMPANY_NAME, DISTRIBUTOR_NAME),
FOREIGN KEY (COMPANY_NAME) REFERENCES COMPANY (COMPANY_NAME),
FOREIGN KEY (DISTRIBUTOR_NAME) REFERENCES DISTRIBUTOR (DISTRIBUTOR_NAME)
);

#6
#Table: Produce (Relationship)
CREATE TABLE PRODUCE(
COMPANY_NAME VARCHAR(25) NOT NULL,
SERIAL_CODE BIGINT NOT NULL,
PRIMARY KEY (COMPANY_NAME,SERIAL_CODE),
FOREIGN KEY (COMPANY_NAME) REFERENCES COMPANY (COMPANY_NAME),
FOREIGN KEY (SERIAL_CODE) REFERENCES DRUG (SERIAL_CODE)
);

#7
#Table: Prescribe (Relationship)
CREATE TABLE PRESCRIBE(
COMPANY_NAME VARCHAR(25) NOT NULL,
SERIAL_CODE BIGINT NOT NULL,
DOCTOR_SSN INT NOT NULL,
PATIENT_SSN INT,
DOCTOR_NAME VARCHAR(25),
DATE_OF_PRESCRIPTION DATE,
PRIMARY KEY (COMPANY_NAME,SERIAL_CODE,DOCTOR_SSN),
FOREIGN KEY (DOCTOR_SSN) REFERENCES DOCTOR (DOCTOR_SSN),
FOREIGN KEY (COMPANY_NAME) REFERENCES COMPANY (COMPANY_NAME),
FOREIGN KEY (SERIAL_CODE) REFERENCES DRUG (SERIAL_CODE)
);

#8
#Table: Visit (Relationship)
CREATE TABLE VISIT(
SALESMAN_SSN INT,
DOCTOR_SSN INT,
PRIMARY KEY (SALESMAN_SSN, DOCTOR_SSN),
FOREIGN KEY (SALESMAN_SSN) REFERENCES SALESMAN (SALESMAN_SSN),
FOREIGN KEY (DOCTOR_SSN) REFERENCES DOCTOR (DOCTOR_SSN)
);

#9
#Table: Go To (Relationship)
CREATE TABLE GOTO(
DOCTOR_SSN INT,
PATIENT_SSN INT,
PRIMARY KEY (PATIENT_SSN, DOCTOR_SSN),
FOREIGN KEY (PATIENT_SSN) REFERENCES PATIENT (PATIENT_SSN),
FOREIGN KEY (DOCTOR_SSN) REFERENCES DOCTOR (DOCTOR_SSN)
);
commit;
