#If you recreated this, remember to remove the last ',' in the file
INSERT INTO BUY(COMPANY_NAME, DISTRIBUTOR_NAME)VALUES 
VALUES( 'Amgen', ' McKesson Corporation ' ),
VALUES( 'Amgen', ' Alfresa holdings ' ),
VALUES( 'Amgen', ' AmerisourceBergen Corp ' ),
VALUES( 'AstraZeneca', ' Cardinal Health ' ),
VALUES( 'AstraZeneca', ' CR Pharmaceutical Group ' ),
VALUES( 'AstraZeneca', ' Kingworld Medicines Group Ltd ' ),
VALUES( 'Bayer', ' MEDIPAL HOLDINGS ' ),
VALUES( 'Bayer', ' Profarma Distribuidora de Produ ' ),
VALUES( 'Bayer', ' Realcan Pharmaceutical Group Co ' ),
VALUES( 'GSK', ' Shanghai Pharmaceuticals Holding Co ' ),
VALUES( 'GSK', ' SINOPHARM HOLDING CO LTD ' ),
VALUES( 'GSK', ' Walgreens Boots Alliance ' ),
VALUES( 'Johnson n Johnson', ' Zhejiang Intâ€™l Group Co. Ltd ' ),
VALUES( 'Johnson n Johnson', ' SUZUKEN ' ),
VALUES( 'Johnson n Johnson', ' The phoenix group pharmaceuticals ' ),
VALUES( 'Novartis', ' Smith Drug Company ' ),
VALUES( 'Novartis', ' Prodigy Health ' ),
VALUES( 'Novartis', ' Ohki Healthcare Holdings Co. Ltd ' ),
VALUES( 'Novo Nordisk', ' North Carolina Mutual Wholesale Drug ' ),
VALUES( 'Novo Nordisk', ' Morris & Dickson ' ),
VALUES( 'Novo Nordisk', ' Mawdsleys ' ),
VALUES( 'Opella M.E.P.E.', ' HyGen Pharmaceuticals, Inc ' ),
VALUES( 'Opella M.E.P.E.', ' Fortissa ' ),
VALUES( 'Opella M.E.P.E.', ' CuraScript Special ' ),
VALUES( 'Pfizer', ' Capital Wholesale Drug Company ' ),
VALUES( 'Pfizer', ' AAH Pharmaceuticals Ltd ' ),
VALUES( 'Pfizer', ' Drogueria Betances, Inc ' ),
VALUES( 'Pfizer Hellas A.E.', ' EzriRx ' ),
VALUES( 'Pfizer Hellas A.E.', ' FCL Health Solutions ' ),
VALUES( 'Pfizer Hellas A.E.', ' Firstline Pharma Ltd ' ),
VALUES( 'Roche', ' Goodwill Pharma ' ),
VALUES( 'Roche', ' H.D. Smith ' ),
VALUES( 'Roche', ' Henry Schein Inc ' ),
VALUES( 'Sanofi', ' Karo Pharma ' ),
VALUES( 'Sanofi', ' Letco Medical ' ),
VALUES( 'Sanofi', ' Masters Pharmaceutical ' ),
VALUES( 'Uni-Pharma A.E.', ' Medline Industries ' ),
VALUES( 'Uni-Pharma A.E.', ' Mockingbird Pharma ' ),
VALUES( 'Uni-Pharma A.E.', ' Mutual Drug ' )
;
