#1
#Table: Company
CREATE TABLE COMPANY(
COMPANY_NAME VARCHAR(25) NOT NULL,
HQ_ADDRESS VARCHAR(25),
INCOME_OUTCOME INT,
NUMBER_OF_SALESMEN INT,
NUMBER_OF_DISTRIBUTORS INT,
NUMBER_OF_FACTORIES INT,
RATE INT,
PRIMARY KEY(COMPANY_NAME)
);
#2
#Table: State Deposit of Pharmaceuticals (Entity)
CREATE TABLE STATE_DEPOSIT_OF_PHARMACEUTICALS(
SDOP_NAME VARCHAR(25) NOT NULL,
RANGE_SDOP INT,
CAPACITY_SDOP INT,
LOCATION VARCHAR(25),
PRIMARY KEY (SDOP_NAME)
);
#3
#Table: Doctor (Entity)
CREATE TABLE DOCTOR(
DOCTOR_SSN INT NOT NULL,
DOCTOR_NAME VARCHAR(25),
AGE INT,
EXPERIENCE INT,
SPECIALTY VARCHAR(25),
PRIMARY KEY (DOCTOR_SSN)
);
#4
#Table: Patient (Entity)
CREATE TABLE PATIENT(
PATIENT_SSN INT NOT NULL,
PATIENT_NAME VARCHAR(25),
AGE INT,
GENDER BOOLEAN,
PHONE_NUMBER BIGINT,
PRIMARY KEY (PATIENT_SSN)
);
#5
#Table: Drugs (Entity)
CREATE TABLE DRUGS(
SERIAL_CODE BIGINT NOT NULL,
COMPANY_NAME VARCHAR(25) NOT NULL,
DRUG_NAME VARCHAR(25),
TYPE VARCHAR(25),
APPROVAL BOOLEAN,
PRICE DECIMAL(8,3),
PRIMARY KEY(SERIAL_CODE,COMPANY_NAME),
FOREIGN KEY(COMPANY_NAME) REFERENCES COMPANY(COMPANY_NAME)
);
#6
#Table: Salesman
CREATE TABLE SALESMAN(
SALESMAN_NAME VARCHAR(25),
SALESMAN_SSN INT NOT NULL,
COMPANY_NAME VARCHAR(25),
SERIAL_CODE BIGINT NOT NULL,
EXPERIENCE INT,
SALARY DECIMAL(8,3),
PRIMARY KEY(SALESMAN_SSN),
FOREIGN KEY(COMPANY_NAME) REFERENCES COMPANY(COMPANY_NAME),
FOREIGN KEY (SERIAL_CODE) REFERENCES DRUGS(SERIAL_CODE)
);
#7
#Table: Distributor
CREATE TABLE DISTRIBUTOR(
DISTRIBUTOR_NAME VARCHAR(25) NOT NULL,
POINTS INT,
CAPACITY_D INT,
TIME_OF_D INT,
RANGE_D INT,
PRIMARY KEY(DISTRIBUTOR_NAME)
);
#8
#Table: Prescription (Entity)
CREATE TABLE PRESCRIPTION(
COMPANY_NAME VARCHAR(25) NOT NULL,
SERIAL_CODE BIGINT NOT NULL,
DISEASE_CODE CHAR(3),
PATIENT_SSN INT NOT NULL,
DATE_OF_PRESCRIPTION DATE,
PRIMARY KEY (SERIAL_CODE, COMPANY_NAME),
FOREIGN KEY (SERIAL_CODE) REFERENCES DRUGS (SERIAL_CODE),
FOREIGN KEY (COMPANY_NAME) REFERENCES COMPANY (COMPANY_NAME)
);

#1
#Table: Consume (Relationship)
CREATE TABLE CONSUME(
PATIENT_SSN INT NOT NULL,
COMPANY_NAME VARCHAR(25) NOT NULL,
SERIAL_CODE BIGINT NOT NULL,
FREQUENCY INT,
PRIMARY KEY (PATIENT_SSN, COMPANY_NAME, SERIAL_CODE),
FOREIGN KEY (PATIENT_SSN) REFERENCES PATIENT(PATIENT_SSN),
FOREIGN KEY (SERIAL_CODE) REFERENCES DRUGS(SERIAL_CODE),
FOREIGN KEY (COMPANY_NAME) REFERENCES COMPANY(COMPANY_NAME)
);

#2
#Table: Distribute (Relationship)
CREATE TABLE DISTRIBUTE(
DISTRIBUTOR_NAME VARCHAR(25) NOT NULL,
COMPANY_NAME VARCHAR(25) NOT NULL,
SERIAL_CODE BIGINT NOT NULL,
TIME_OF_D INT,
PRIMARY KEY (DISTRIBUTOR_NAME, COMPANY_NAME, SERIAL_CODE),
FOREIGN KEY (DISTRIBUTOR_NAME) REFERENCES DISTRIBUTOR(DISTRIBUTOR_NAME),
FOREIGN KEY (COMPANY_NAME) REFERENCES COMPANY(COMPANY_NAME),
FOREIGN KEY (SERIAL_CODE) REFERENCES DRUGS(SERIAL_CODE)
);

#3
#Table: Sell (Relationship)
CREATE TABLE SELL(
SDOP_NAME VARCHAR(25) NOT NULL,
DISTRIBUTOR_NAME VARCHAR(25) NOT NULL,
PRIMARY KEY (SDOP_NAME, DISTRIBUTOR_NAME),
FOREIGN KEY (SDOP_NAME) REFERENCES STATE_DEPOSIT_OF_PHARMACEUTICALS(SDOP_NAME),
FOREIGN KEY (DISTRIBUTOR_NAME) REFERENCES DISTRIBUTOR (DISTRIBUTOR_NAME)
);

#4
#Table: Provides (Relationship)
CREATE TABLE PROVIDES(
SDOP_NAME VARCHAR(25) NOT NULL,
SERIAL_CODE BIGINT NOT NULL,
PRIMARY KEY (SDOP_NAME, SERIAL_CODE),
FOREIGN KEY (SDOP_NAME) REFERENCES STATE_DEPOSIT_OF_PHARMACEUTICALS (SDOP_NAME),
FOREIGN KEY (SERIAL_CODE) REFERENCES DRUGS (SERIAL_CODE)
);

#5
#Table: Buy (Relationship)
CREATE TABLE BUY(
COMPANY_NAME VARCHAR(25) NOT NULL,
DISTRIBUTOR_NAME VARCHAR(25) NOT NULL,
PRIMARY KEY (COMPANY_NAME, DISTRIBUTOR_NAME),
FOREIGN KEY (COMPANY_NAME) REFERENCES COMPANY (COMPANY_NAME),
FOREIGN KEY (DISTRIBUTOR_NAME) REFERENCES DISTRIBUTOR (DISTRIBUTOR_NAME)
);

#6
#Table: Produce (Relationship)
CREATE TABLE PRODUCE(
COMPANY_NAME VARCHAR(25) NOT NULL,
SERIAL_CODE BIGINT NOT NULL,
PRIMARY KEY (COMPANY_NAME,SERIAL_CODE),
FOREIGN KEY (COMPANY_NAME) REFERENCES COMPANY (COMPANY_NAME),
FOREIGN KEY (SERIAL_CODE) REFERENCES DRUGS (SERIAL_CODE)
);

#7
#Table: Prescribe (Relationship)
CREATE TABLE PRESCRIBE(
COMPANY_NAME VARCHAR(25) NOT NULL,
SERIAL_CODE BIGINT NOT NULL,
DOCTOR_SSN INT NOT NULL,
PATIENT_SSN INT,
DOCTOR_NAME VARCHAR(25),
DATE_OF_PRESCRIPTION DATE,
PRIMARY KEY (COMPANY_NAME,SERIAL_CODE,DOCTOR_SSN),
FOREIGN KEY (DOCTOR_SSN) REFERENCES DOCTOR (DOCTOR_SSN),
FOREIGN KEY (COMPANY_NAME) REFERENCES COMPANY (COMPANY_NAME),
FOREIGN KEY (SERIAL_CODE) REFERENCES DRUGS (SERIAL_CODE)
);

#8
#Table: Visit (Relationship)
CREATE TABLE VISIT(
SALESMAN_SSN INT,
DOCTOR_SSN INT,
PRIMARY KEY (SALESMAN_SSN, DOCTOR_SSN),
FOREIGN KEY (SALESMAN_SSN) REFERENCES SALESMAN (SALESMAN_SSN),
FOREIGN KEY (DOCTOR_SSN) REFERENCES DOCTOR (DOCTOR_SSN)
);

#9
#Table: Go To (Relationship)
CREATE TABLE GOTO(
DOCTOR_SSN INT,
PATIENT_SSN INT,
PRIMARY KEY (PATIENT_SSN, DOCTOR_SSN),
FOREIGN KEY (PATIENT_SSN) REFERENCES PATIENT (PATIENT_SSN),
FOREIGN KEY (DOCTOR_SSN) REFERENCES DOCTOR (DOCTOR_SSN)
);
commit;
